environments:
  default:
    install:
      - terminator
      - google-chrome-stable
      - sublime-text
    clone:
      - repository: git@github.com:jacsmith21/school.git
        to: ~/git
  python:
    install:
      - python-tk
      - pycharm
      - python3-dev
  web:
    install:
      - webstorm
      - node
  work:
    clone:
      - repository: git@bitbucket.org:eigeninnovations/eigen-models.git
        to: ~/git


aliases:
  default:
    aliases:
      tb_default: tensorboard --logdir=TRAIN:training,VALIDATION:validation
      which-vga: lspci -vnnn | perl -lne \'print if /^\d+\:.+(\[\S+\:\S+\])/\' | grep VGA
      swap: setxkbmap -option altwin:swap_alt_win
      rollbacK: setxkbmap -option
      startup: echo "startup is not defined"
      source-it: source ~/.bashrc
      scratch: cd ~/scratch
      gits: cd ~/git
      hugo-deploy: hugo server --port=80 --baseUrl=http://IP --bind=0.0.0.0
      restart-eva: sudo systemctl restart eva
      sologs: less /opt/eigen/logs/smartobject.log
      mkvirtualenv: mkvirtualenv --python=/usr/bin/python3
      models: cd ~/git/eigen-models
      startmongo: sudo service mongod start

    links:
      -
        this: /usr/bin/cmake
        that: /usr/local/bin/cmake

    functions:
      parse_git_branch:
        - git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'

    exports: 
      PS1: >
        \u@\sh \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ 
      PATH: $PATH:~/bin:~/.local/bin:/opt/cmake/bin
      PYTHONPATH: $PYTHONPATH:~/git/eigen-models

    keys:
      - ~/.ssh/EigenAWS.pem
      - ~/.ssh/id_rsa

    sources:
      - ~/.local/bin/virtualenvwrapper.sh

    eval:
      - "$(_OVERSEE_COMPLETE=source oversee)"

  local:
    inherit: default
    aliases:
      startup: subl ~/.oversee.yaml

  remote:
    inherit: default
    aliases:
      startup: micro ~/.oversee.yaml


jetbrains:
  - colors/_@user_Darcula.icls
  - keymaps/Default for XWin copy.xml


gitignores:
  jetbrains: https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore


install:
  google-chrome-stable:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
  - apt-get

  git:
    - apt-get

  atom:
    - repository: ppa:webupd8team/atom
    - apt-get

  pip35:
    - install python3-setuptools
    - sudo easy_install3 pip

  terminator:
    - repository: ppa:gnome-terminator/nightly
    - apt-get

  default-jdk:
    - apt-get

  nvm:
    - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  
  node:
    - install:
      - nvm
    - nvm install node

  postman:
    - wget https://dl.pstmn.io/download/latest/linux64 -O postman.tar.gz
    - sudo tar -xzf postman.tar.gz -C /opt
    - rm postman.tar.gz
    - sudo ln -s /opt/Postman/Postman /usr/bin/postman
    - sudo apt-get install libgconf-2-4
    - >
      cat > ~/.local/share/applications/postman.desktop <<EOL
      [Desktop Entry]
      Encoding=UTF-8
      Name=Postman
      Exec=postman
      Icon=/opt/Postman/resources/app/assets/icon.png
      Terminal=false
      Type=Application
      Categories=Development;
      EOL

  hipchat:
    - wget https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client/pool/HipChat4-4.0.1517-Linux.deb
    - sudo dpkg -i HipChat4-4.0.1517-Linux.deb
    - rm -f HipChat4-4.0.1517-Linux.deb

  sublime-text:
    - wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
    - echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
    - apt-get

  pycharm:
    - jetbrains: PCP

  webstorm:
    - jetbrains: WS

  idea:
    - jetbrains: IIU

  datagrip:
    - jetbrains: DG

  clion:
    - jetbrains: CL

  python-tk:
    # Necessary to run a whole bunch of python stuff
    - apt-get

  python3-dev:
    # Necessary package for installing cython
    - apt-get
  
  virtualenvwrapper:
    - pip install virtualenvwrapper
  
  solaar:
    - repository: ppa:daniel.pavel/solaar
    - apt-get

  mongodb-org:
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
    - apt-get

  mongocompass:
    - wget https://downloads.mongodb.com/compass/mongodb-compass_1.12.5_amd64.deb
    - sudo dpkg -i mongodb-compass_1.12.5_amd64.deb
    - rm mongodb-compass_1.12.5_amd64.deb

gitignore:
  python:
    - __pycache__/
    - .pytest_cache
    - dist/
    - "*.pyc"
    - <name>.egg-info/
